Updated action code for UAT and Prod

diff --git a/.github/workflows/prod_create_deploy_docker_image.yml b/.github/workflows/prod_create_deploy_docker_image.yml
--- a/.github/workflows/prod_create_deploy_docker_image.yml
+++ b/.github/workflows/prod_create_deploy_docker_image.yml
@@ -4,9 +4,13 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
     inputs:
-      tag:
-        description: "Tag to deploy"
+      #tag:
+      #  description: "Tag to deploy"
+      #  required: true
+      confirmation:
+        description: "Type YES to confirm deployment"
         required: true
+        default: "NO"
 
 jobs:
   build:
@@ -17,13 +21,36 @@ jobs:
       packages: write
 
     steps:
+      - name: Check Branch
+        id: check_branch
+        run: |
+          if [[ "${{ github.ref }}" != "refs/heads/master" ]]; then
+            echo "Error: This workflow can only be triggered from the master branch."
+            exit 1  # Exit with an error if the branch is not master
+          fi
+
+      - name: Check Confirmation
+        id: check_confirmation
+        run: |
+          if [[ "${{ github.event.inputs.confirmation }}" != "YES" ]]; then
+            echo "Error: You must type 'YES' to confirm deployment."
+            exit 1  # Exit with an error if the confirmation is not 'YES'
+          fi
+          echo "Confirmation received. Proceeding with deployment."
+
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.inputs.tag }}
 
+      # Set up Node.js 20
+      - name: Set up Node.js 20
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           distribution: "adopt"
           java-version: "17"
@@ -58,7 +85,7 @@ jobs:
         run: docker build --file Dockerfile --tag ghcr.io/lb-advisors/springboot-prod:latest --build-arg COMMIT_MESSAGE="${{ steps.commit_message.outputs.message }}" --build-arg COMMIT_HASH="${{ steps.commit_hash.outputs.hash }}" --build-arg BUILD_TIME="${{ steps.build_time.outputs.time }}" .
 
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ secrets.DOCKER_USERNAME }}
@@ -74,9 +101,9 @@ jobs:
           name: spring-boot-app
           path: target/*.jar
 
-      # trigger render.com docker image deployment
-      #- name: Deploy to Render
-      #  uses: fjogeleit/http-request-action@v1
-      #  with:
-      #    url: ${{ secrets.RENDER_TRIGGER_URL }}
-      #    method: "GET"
+      #trigger render.com docker image deployment
+      - name: Deploy to Render
+        uses: fjogeleit/http-request-action@v1
+        with:
+          url: ${{ secrets.RENDER_PROD_TRIGGER_URL }}
+          method: "GET"
