Run develop only on UAT

diff --git a/.github/workflows/uat_create_deploy_docker_image.yml b/.github/workflows/uat_create_deploy_docker_image.yml
--- a/.github/workflows/uat_create_deploy_docker_image.yml
+++ b/.github/workflows/uat_create_deploy_docker_image.yml
@@ -20,6 +20,14 @@ jobs:
       packages: write
 
     steps:
+      - name: Check Branch
+        id: check_branch
+        run: |
+          if [[ "${{ github.ref }}" != "refs/heads/develop" ]]; then
+            echo "Error: This workflow can only be triggered from the develop branch."
+            exit 1  # Exit with an error if the branch is not develop
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@v4
 
