Force develop branch

diff --git a/.github/workflows/uat_create_deploy_docker_image.yml b/.github/workflows/uat_create_deploy_docker_image.yml
--- a/.github/workflows/uat_create_deploy_docker_image.yml
+++ b/.github/workflows/uat_create_deploy_docker_image.yml
@@ -23,9 +23,9 @@ jobs:
       - name: Check Branch
         id: check_branch
         run: |
-          if [[ "${{ github.ref }}" != "refs/heads/develop" ]]; then
-            echo "Error: This workflow can only be triggered from the develop branch."
-            exit 1  # Exit with an error if the branch is not develop
+          if [[ "${{ github.event.inputs.branch }}" != "develop" ]]; then
+            echo "Error: This workflow can only be triggered for the develop branch."
+            exit 1
           fi
 
       - name: Checkout repository
